export const sampleObj = [
  {
    adult: false,
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    popularity: 678.912,
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 8.7,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: "/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
    genre_ids: [28, 10749, 35],
    id: 758009,
    original_language: "en",
    original_title: "Shotgun Wedding",
    overview:
      "Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.",
    popularity: 922.343,
    poster_path: "/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg",
    release_date: "2022-12-28",
    title: "Shotgun Wedding",
    video: false,
    vote_average: 6.3,
    vote_count: 673,
  },
  {
    adult: false,
    backdrop_path: "/2E6pIbJien7B9yWpaz8Yd2njzUI.jpg",
    genre_ids: [18, 27],
    id: 1026563,
    original_language: "es",
    original_title: "13 exorcismos",
    overview:
      "After participating in a séance, young Laura begins to behave strangely. Alarmed, her parents ask Father Olmedo, one of the few exorcists authorized by the Vatican to intervene in cases of demonic possession, for help.",
    popularity: 1608.438,
    poster_path: "/8LpnMIqpRiwxpbGR33ALCmVl7gj.jpg",
    release_date: "2022-11-04",
    title: "13 Exorcisms",
    video: false,
    vote_average: 6.5,
    vote_count: 17,
  },
];
